/** Converts stored documents (snake_case) into the plain domain objects the core engine and pages use. */
const num = (value) => (value === null || value === undefined ? value : Number(value));

export const mapSession = (row) => ({
  id: row._id ?? row.id,
  userId: row.user_id,
  startingCapital: num(row.starting_capital),
  target: num(row.target),
  minPayoutPct: num(row.min_payout_pct),
  baseAmount: num(row.base_amount),
  dailyLossLimitPct: num(row.daily_loss_limit_pct),
  dailyLossLimitAmount: num(row.daily_loss_limit_amount),
  consecutiveLossLimit: num(row.consecutive_loss_limit),
  recoveryExtraPct: num(row.recovery_extra_pct),
  profitReinvestPct: num(row.profit_reinvest_pct),
  maxTradePct: num(row.max_trade_pct),
  accuracyFloorPct: num(row.accuracy_floor_pct),
  accuracyMinTrades: num(row.accuracy_min_trades),
  accuracyExtraLosses: num(row.accuracy_extra_losses),
  profitProtectStartPct: num(row.profit_protect_start_pct),
  profitGivebackPct: num(row.profit_giveback_pct),
  profitLossStreak: num(row.profit_loss_streak),
  profitWarnPoints: num(row.profit_warn_points),
  profitStopPoints: num(row.profit_stop_points),
  profitPeakTrades: num(row.profit_peak_trades),
  profitPeakMinutes: num(row.profit_peak_minutes),
  profitExtraLosses: num(row.profit_extra_losses),
  lastMilestonePct: row.last_milestone_pct,
  lockReason: row.lock_reason,
  status: row.status,
  safetyLockedUntil: row.safety_locked_until,
  startedAt: row.started_at,
  closedAt: row.closed_at,
});

export const mapTrade = (row) => ({
  id: row._id ?? row.id,
  seq: row.seq,
  result: row.result,
  amount: num(row.amount),
  payoutPct: num(row.payout_pct),
  pnl: num(row.pnl),
  pair: row.pair ?? null,
  isOtc: Boolean(row.is_otc),
  timeframe: row.timeframe ?? null,
  createdAt: row.created_at,
});

export const mapDailyStat = (row) => ({
  sessionId: row.session_id,
  statDate: row.stat_date,
  startingCapital: num(row.starting_capital),
  closingCapital: num(row.closing_capital),
  target: num(row.target),
  totalTrades: row.total_trades,
  wins: row.wins,
  losses: row.losses,
  totalProfit: num(row.total_profit),
  totalLoss: num(row.total_loss),
  netPnl: num(row.net_pnl),
  maxDrawdown: num(row.max_drawdown),
  longestWinStreak: row.longest_win_streak,
  longestLossStreak: row.longest_loss_streak,
  targetAchievedPct: num(row.target_achieved_pct),
  limitReached: row.limit_reached,
});
